model_name: ssm_skd
name: ${model_name}_${dataset_variant}
out_dir: ${msd_root}/models/${name}
checkpoint_dir: ${msd_root}/models/${model_name}_3dshapes
device: cuda
load_model: best
dataset: configurations/datasets/vlm_annotated/ufs_3dshapes.yaml
training_evaluation: configurations/evaluations/video_vlm_training_evaluation.yaml
testing_evaluation: configurations/evaluations/video_vlm_testing_evaluation.yaml
batch_size: 32
test_batch_size: 500
latent_explorer_cfg:
  name: PredictorLatentExplorer
  parameters:
    batch_exploration: true
model:
  name: SsmSkd
  parameters:
    in_dim: 3
    k_dim: 28
    hidden_dim: 200
    data_type: video
trainer:
  name: SsmSkdTrainer
  save_model: true
  parameters:
    w_rec: 16.0
    w_pred: 4.0
    w_eigs: 4.0
    dynamic_thresh: 0.875
    gradient_clip_val: 5
  resume: false
  scheduler:
    name: StepLR
    parameters:
      step_size: 250
      gamma: 0.5
  optimizer:
    name: Adam
    parameters:
      lr: 0.001
  epochs:
    start: 1
    end: 500
  verbose: 5
